package server;

public enum JSONEventsE {
	QUEUEFORGAME, LOGIN, GAMESTART, SHUFFLE, USERLIST, STATISTICS, QUEUENUMBER, FAIL, MOVEORDER, MAKEMOVE, FLUSH, CARDBROADCAST, ROUNDWINNER, LOGOUT, GETGAMEMODE, GAMEWINNER, SHOWSCORE
}
